const API='http://127.0.0.1:8765';
const V=['dashboard','clientes','ferramentas','emprestimos','devolucoes','historico'];
function notify(t,e=false){const m=document.getElementById('msg');m.textContent=t;m.style.color=e?'red':'green'}
async function req(p,o={}){try{const r=await fetch(API+p,{headers:{'Content-Type':'application/json'},...o});if(!r.ok)throw new Error((await r.text())||'erro');return await r.json()}catch(e){notify('Falha de conexão com a API: '+e.message,true);throw e}}
function show(id){V.forEach(v=>document.getElementById(v).style.display=v===id?'block':'none');load(id)}
async function load(id){if(id==='dashboard'){const d=await req('/dashboard');document.getElementById(id).innerHTML=`<h3>Dashboard</h3><p>Disponível: ${d.total_disponivel} | Emprestado: ${d.total_emprestado} | Clientes: ${d.total_clientes}</p>`}
if(id==='clientes'){const l=await req('/clientes');document.getElementById(id).innerHTML=`<h3>Clientes</h3><input id='cq' placeholder='buscar' oninput='load("clientes")'><button onclick='novoCliente()'>Novo</button><table><tr><th>Nome</th><th>Status</th><th>Ação</th></tr>${l.filter(x=>x.nome.toLowerCase().includes((document.getElementById('cq')?.value||'').toLowerCase())).map(c=>`<tr><td>${c.nome}</td><td>${c.ativo?'Ativo':'Inativo'}</td><td><button onclick='toggleCliente(${c.id})'>Alternar</button></td></tr>`).join('')}</table>`}
if(id==='ferramentas'){const l=await req('/ferramentas');document.getElementById(id).innerHTML=`<h3>Ferramentas</h3><input id='fq' placeholder='buscar' oninput='load("ferramentas")'><button onclick='novaFerramenta()'>Nova</button><table><tr><th>Nome</th><th>Total</th><th>Disp.</th><th>Status</th><th>Ação</th></tr>${l.filter(x=>x.nome.toLowerCase().includes((document.getElementById('fq')?.value||'').toLowerCase())).map(f=>`<tr><td>${f.nome}</td><td>${f.quantidade_total}</td><td>${f.quantidade_disponivel}</td><td>${f.ativo?'Ativa':'Inativa'}</td><td><button onclick='toggleFerramenta(${f.id})'>Alternar</button></td></tr>`).join('')}</table>`}
if(id==='emprestimos'){const cs=await req('/clientes');const fs=await req('/ferramentas');const ab=await req('/emprestimos/abertos');document.getElementById(id).innerHTML=`<h3>Empréstimos</h3><select id='ec'>${cs.filter(c=>c.ativo).map(c=>`<option value='${c.id}'>${c.nome}</option>`)}</select><select id='ef'>${fs.filter(f=>f.ativo).map(f=>`<option value='${f.id}'>${f.nome} (${f.quantidade_disponivel})</option>`)}</select><input id='eq' type='number' min='1' value='1'><button onclick='emprestar()'>Registrar</button><h4>Abertos</h4><ul>${ab.map(e=>`<li>#${e.id} ferramenta:${e.ferramenta_id} cliente:${e.cliente_id} pendente:${e.quantidade-e.quantidade_devolvida}</li>`).join('')}</ul>`}
if(id==='devolucoes'){const ab=await req('/emprestimos/abertos');document.getElementById(id).innerHTML=`<h3>Devoluções</h3><select id='did'>${ab.map(e=>`<option value='${e.id}'>#${e.id} pendente ${e.quantidade-e.quantidade_devolvida}</option>`)}</select><input id='dq' type='number' min='1' value='1'><button onclick='devolver()'>Registrar</button>`}
if(id==='historico'){const h=await req('/historico');document.getElementById(id).innerHTML=`<h3>Histórico</h3><table><tr><th>Tipo</th><th>Cliente</th><th>Ferramenta</th><th>Qtd</th><th>Data</th><th>Obs</th></tr>${h.map(m=>`<tr><td>${m.tipo}</td><td>${m.cliente_id}</td><td>${m.ferramenta_id}</td><td>${m.quantidade}</td><td>${new Date(m.criado_em).toLocaleString()}</td><td>${m.observacao||''}</td></tr>`).join('')}</table>`}}
async function novoCliente(){const nome=prompt('Nome do cliente');if(!nome)return;await req('/clientes',{method:'POST',body:JSON.stringify({nome})});notify('Cliente cadastrado');load('clientes')}
async function toggleCliente(id){await req(`/clientes/${id}/toggle`,{method:'PATCH'});notify('Cliente atualizado');load('clientes')}
async function novaFerramenta(){const nome=prompt('Nome da ferramenta');const qtd=Number(prompt('Quantidade total','1'));if(!nome||!qtd)return;await req('/ferramentas',{method:'POST',body:JSON.stringify({nome,quantidade_total:qtd})});notify('Ferramenta cadastrada');load('ferramentas')}
async function toggleFerramenta(id){await req(`/ferramentas/${id}/toggle`,{method:'PATCH'});notify('Ferramenta atualizada');load('ferramentas')}
async function emprestar(){await req('/emprestimos',{method:'POST',body:JSON.stringify({cliente_id:Number(ec.value),ferramenta_id:Number(ef.value),quantidade:Number(eq.value)})});notify('Empréstimo registrado');load('emprestimos')}
async function devolver(){await req('/devolucoes',{method:'POST',body:JSON.stringify({emprestimo_id:Number(did.value),quantidade:Number(dq.value)})});notify('Devolução registrada');load('devolucoes')}
show('dashboard');
